before:
  hooks:
    - make ensure
builds:
- binary: go-cron
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X main.build={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }}
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
archives:
- replacements:
    darwin: macos
    linux: linux
    windows: windows
    386: 32-bit
    amd64: 64-bit
  format: zip
  files:
    - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}_{{ .ShortCommit }}"
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
